import type { OhlcvBar } from "../types";
export type WyckoffPhase = "accumulation" | "spring" | "test" | "markup" | "distribution" | "undetermined";
export type WyckoffEvent = "PS" | "SC" | "AR" | "ST" | "Spring" | "Test" | "SOS" | "LPS" | "BU" | "UTAD" | "DIST" | "LPSY";
export interface WyckoffEventDetail { event: WyckoffEvent; date: string; index: number; price: number; volume: number; strength: number; }
export interface WyckoffResult { phase: WyckoffPhase; rangeHigh: number | null; rangeLow: number | null; rangeStartDate: string | null; rangeEndDate: string | null; events: WyckoffEventDetail[]; springDate: string | null; testDate: string | null; markupDate: string | null; dataQuality: "ESTIMATED"; phaseA?: string; phaseB?: string; phaseC?: string; phaseD?: string; phaseE?: string; }
const RL = 50; const RMW = 0.15; const RMB = 30;
function avgV(bars: OhlcvBar[], n: number): number { const r = bars.slice(-n); return r.length === 0 ? 0 : r.reduce((s, b) => s + b.volume, 0) / r.length; }
function findTR(bars: OhlcvBar[]): { high: number; low: number; startIdx: number; endIdx: number } | null { if (bars.length < RMB) return null; const ws = Math.min(RL, Math.floor(bars.length / 3)); let b: { high: number; low: number; startIdx: number; endIdx: number; width: number } | null = null; for (let s = 0; s < bars.length - ws; s += 5) { const w = bars.slice(s, s + ws); const h = Math.max(...w.map(x => x.high)); const l = Math.min(...w.map(x => x.low)); const wi = (h - l) / l; if (wi <= RMW && (!b || wi < b.width)) b = { high: h, low: l, startIdx: s, endIdx: s + ws - 1, width: wi }; } return b ? { high: b.high, low: b.low, startIdx: b.startIdx, endIdx: b.endIdx } : null; }
function isSp(v: number, a: number) { return v > a * 2; } function isL(v: number, a: number) { return v < a * 0.6; }
export function classifyWyckoffPhase(bars: OhlcvBar[]): WyckoffResult { const base: WyckoffResult = { phase: "undetermined", rangeHigh: null, rangeLow: null, rangeStartDate: null, rangeEndDate: null, events: [], springDate: null, testDate: null, markupDate: null, dataQuality: "ESTIMATED" }; if (bars.length < RMB) return base; const m20 = avgV(bars, 20); const r = findTR(bars); if (!r) return base; base.rangeHigh = r.high; base.rangeLow = r.low; base.rangeStartDate = bars[r.startIdx].date; base.rangeEndDate = bars[r.endIdx].date; const rb = bars.slice(r.startIdx, r.endIdx + 1); const ev: WyckoffEventDetail[] = []; let pI = -1, sI = -1, spI = -1, tI = -1, soI = -1, lI = -1; const lp = Math.min(...rb.slice(0, 10).map(b => b.low)); for (let i = 0; i < rb.length; i++) { const b = rb[i]; if (pI === -1 && b.volume > m20 * 1.5 && b.close > b.open) { pI = i; ev.push({ event: "PS", date: b.date, index: r.startIdx + i, price: b.low, volume: b.volume, strength: 0.6 }); } if (sI === -1 && isSp(b.volume, m20) && b.close < b.open * 0.97) { sI = i; ev.push({ event: "SC", date: b.date, index: r.startIdx + i, price: b.low, volume: b.volume, strength: 0.9 }); } if (sI >= 0 && spI === -1 && b.low < lp * 1.01 && b.low > lp * 0.98 && isL(b.volume, m20)) { spI = i; ev.push({ event: "Spring", date: b.date, index: r.startIdx + i, price: b.low, volume: b.volume, strength: 0.8 }); base.springDate = b.date; } if (sI >= 0 && tI === -1 && Math.abs(b.low - lp) / lp <= 0.03 && i > sI + 2) { tI = i; ev.push({ event: "ST", date: b.date, index: r.startIdx + i, price: b.low, volume: b.volume, strength: 0.7 }); base.testDate = b.date; } if (i >= (spI >= 0 ? spI + 1 : 0) && soI === -1 && b.close > r.high * 0.98 && b.volume > m20 * 1.3) { soI = i; ev.push({ event: "SOS", date: b.date, index: r.startIdx + i, price: b.high, volume: b.volume, strength: 0.85 }); base.markupDate = b.date; } if (soI >= 0 && lI === -1 && b.low > r.low * 1.02 && b.close < b.open && b.volume < m20) { lI = i; ev.push({ event: "LPS", date: b.date, index: r.startIdx + i, price: b.low, volume: b.volume, strength: 0.75 }); } } if (soI !== -1 && lI !== -1) { base.phase = "markup"; base.phaseA = "PS/SC/AR"; base.phaseB = "Spring/ST"; base.phaseD = "SOS/LPS"; } else if (soI !== -1) { base.phase = "markup"; base.phaseA = "Accumulation"; base.phaseD = "SOS breakout"; } else if (spI !== -1 && tI !== -1) { base.phase = "test"; base.phaseA = "Accumulation"; base.phaseC = "Spring/ST completed"; } else if (spI !== -1) { base.phase = "spring"; base.phaseC = "Spring detected"; } else if (sI !== -1) { base.phase = "accumulation"; base.phaseA = "PS/SC completed"; base.phaseB = "AR in progress"; } else { base.phase = "undetermined"; } base.events = ev; return base; }
export interface WyckoffChartMarker { date: string; price: number; type: WyckoffEvent; label: string; color: string; strength: number; }
export function getWyckoffChartMarkers(res: WyckoffResult): WyckoffChartMarker[] { const c: Record<string,string> = { PS: "#3b82f6", SC: "#ef4444", AR: "#f97316", ST: "#f97316", Spring: "#22c55e", Test: "#eab308", SOS: "#22c55e", LPS: "#84cc16", BU: "#8b5cf6", UTAD: "#ef4444", DIST: "#ef4444", LPSY: "#84cc16" }; return res.events.map(e => ({ date: e.date, price: e.price, type: e.event, label: e.event, color: c[e.event] || "#888", strength: e.strength })); }
export function scoreWyckoffPhase(phase: WyckoffPhase): number { switch (phase) { case "markup": return 1.0; case "spring": return 0.8; case "test": return 0.7; case "accumulation": return 0.5; case "distribution": return 0.3; default: return 0; } }